name: CI/CD Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: YourApp.sln
      Test_Project_Path: YourApp.Tests/YourApp.Tests.csproj
      Wap_Project_Directory: YourApp.Package
      Wap_Project_Path: YourApp.Package/YourApp.Package.wapproj

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Run unit tests
        run: dotnet test "${{ env.Test_Project_Path }}" --configuration ${{ matrix.configuration }}

      - name: Restore solution
        run: msbuild "${{ env.Solution_Name }}" /t:Restore /p:Configuration=${{ matrix.configuration }}

      - name: Decode signing certificate
        shell: pwsh
        run: |
          $bytes = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
          $certPath = Join-Path "${{ env.Wap_Project_Directory }}" "GitHubActionsWorkflow.pfx"
          [IO.File]::WriteAllBytes($certPath, $bytes)

      - name: Build & package MSIX bundle
        run: |
          msbuild "${{ env.Wap_Project_Path }}" /p:Configuration=${{ matrix.configuration }} `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x86|x64" `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:PackageCertificateKeyFile="${{ env.Wap_Project_Directory }}\GitHubActionsWorkflow.pfx" `
            /p:PackageCertificatePassword="${{ secrets.Pfx_Key }}"

      - name: Cleanup certificate
        run: Remove-Item -Path "${{ env.Wap_Project_Directory }}\GitHubActionsWorkflow.pfx"

      - name: Upload MSIX package
        uses: actions/upload-artifact@v4
        with:
          name: msix-package
          path: "${{ env.Wap_Project_Directory }}/AppPackages"
